s = input("write your name")
print(s)
b = input("write your surname")
print(b)
a = input("write your age")
print(a)
print(("my friend ") + s (", or dear ") + b (", you are very young person"))
print("you are only " + a)