a = input("write your name")
print(a)
b = input("write your surname")
print(b)
c = input("write your age")
print(a)
print(("my friend ") + a (", or dear ") + b (", you are very young person"))
print("you are only " + c)